# This is a basic workflow to help you get started with Actions

name: b300115065

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Set Students Environment Variable
      - name: Student ID
        run: |
         echo "STUDENT_ID=b300115065" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs Node
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
    
      # Installs NativeScript
      - uses: hrueger/setup-nativescript@v1.1.0
        with:
          nativescript-version: '7.0.10'
          
      # Create a device
      - name: Emulator for Android development.
        run: |
           # Install the accelerator
           brew install intel-haxm --cask
           # Create the Android device
           echo y | sdkmanager --install "system-images;android-28;google_apis;x86_64"
           # Create the Android device
           echo no | avdmanager create avd --name test --package "system-images;android-28;google_apis;x86_64"
           # Launch the Android device
           ${ANDROID_HOME}/emulator/emulator -avd test -no-audio -no-window &
           # Wait for the device to start
           adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
           # Show the Android device           
           avdmanager list avd
           adb devices

      # Not sure about the pods
      - name: Update pods
        run: pod repo update
      
      # P.Projects
      - name: Check P.Projects
        run: |
          cd P.Projects/$STUDENT_ID
          ns install
          ns run android --justlaunch
