# This is a basic workflow to help you get started with Actions

name: b300116685

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Set Students Environment Variable
      - name: Student ID
        run: |
         echo "STUDENT_ID=b300116685" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs Node
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
    
      # Installs NativeScript
      - uses: hrueger/setup-nativescript@v1.1.0
        with:
          nativescript-version: '7.0.10'
    
      # Not sure about the pods
      - name: Update pods
        run: pod repo update
      
      # First Assignment
      - name: Check 4.NativeScript
        run: |
          cd  4.NativeScript/$STUDENT_ID
          npm install
          ns build ios
          cd ..
      
      # 2nd Assignment
      - name: Check 8.Forms
        run: |
          cd 8.Forms/$STUDENT_ID
          npm install
          ns build ios
          cd ..

      # 3rd Assignment
      - name: Check 9.RxJS
        run: |
          cd 9.RxJS/$STUDENT_ID
          npm install
          ns build ios
          cd ..

      # 4th Assignment
      - name: Check A.Animations
        run: |
          cd A.Animations/$STUDENT_ID
          npm install
          ns build ios
          cd ..
